# ===========================
# Project Information
# ===========================
sonar.projectKey=secure-devsecops-pipeline
sonar.projectName=Secure DevSecOps Pipeline
sonar.projectVersion=1.0

# ===========================
# SonarQube Server
# ===========================
sonar.host.url=http://localhost:9000

# ===========================
# Source Code
# ===========================
sonar.sources=services

# ===========================
# Language
# ===========================
sonar.sourceEncoding=UTF-8

# ===========================
# Python
# ===========================
sonar.python.version=3.14

# ===========================
# Exclusions
# ===========================
sonar.exclusions=**/__pycache__/**,**/.venv/**,**/tests/**,**/*.pyc

# ===========================
# Test Files
# ===========================
sonar.tests=services
sonar.test.inclusions=**/tests/**/*.py

# ===========================
# Coverage
# ===========================
sonar.python.coverage.reportPaths=coverage.xml
