apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.services.user.name }}
  namespace: {{ .Values.namespace }}
automountServiceAccountToken: false

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.services.auth.name }}
  namespace: {{ .Values.namespace }}
automountServiceAccountToken: false

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.services.gateway.name }}
  namespace: {{ .Values.namespace }}
automountServiceAccountToken: false

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.services.notification.name }}
  namespace: {{ .Values.namespace }}
automountServiceAccountToken: false

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.services.logging.name }}
  namespace: {{ .Values.namespace }}
automountServiceAccountToken: false
