apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig

metadata:
  name: devsecops-email
  namespace: devsecops

spec:
  route:
    receiver: devsecops-email
    groupBy:
      - alertname
      - namespace
    groupWait: 10s
    groupInterval: 5m
    repeatInterval: 12h

    matchers:
      - name: namespace
        matchType: "="
        value: devsecops

  receivers:
    - name: devsecops-email

      emailConfigs:
        - to: aashishmalviya2242006@gmail.com
          from: aashishmalviya2242006@gmail.com

          smarthost: smtp.gmail.com:587

          authUsername: aashishmalviya2242006@gmail.com

          authPassword:
            name: alertmanager-gmail
            key: smtp-auth-password

          requireTLS: true
          sendResolved: false
