apiVersion: apps/v1
kind: Deployment

metadata:
  name: logging-service
  namespace: devsecops
  labels:
    app: logging-service

spec:
  replicas: 1

  selector:
    matchLabels:
      app: logging-service

  template:
    metadata:
      labels:
        app: logging-service

    spec:
      containers:
        - name: logging-service

          image: aashu006/devsecops-logging-service:v1
          imagePullPolicy: Always

          ports:
            - containerPort: 8004
              protocol: TCP

          readinessProbe:
            httpGet:
              path: /health
              port: 8004
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 8004
            initialDelaySeconds: 10
            periodSeconds: 20

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"

          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
